<?php
declare(strict_types=1);
use App\Config\Env;use App\Database\Connection;use App\Http\JsonResponse;use App\Http\Request;use App\Repositories\MoneyRepository;use App\Security\Csrf;use App\Services\DatePolicy;use App\Services\MoneyService;use App\Validation\ExpenseValidator;

$autoload=dirname(__DIR__).'/vendor/autoload.php';require is_file($autoload)?$autoload:dirname(__DIR__).'/autoload.php';Env::load(dirname(__DIR__).'/.env');
$origin=Env::get('APP_ORIGIN','http://localhost:5173');$requestOrigin=$_SERVER['HTTP_ORIGIN']??'';if($requestOrigin!==''&&hash_equals($origin,$requestOrigin)){header("Access-Control-Allow-Origin: $origin");header('Access-Control-Allow-Credentials: true');header('Vary: Origin');}elseif($requestOrigin!==''){JsonResponse::error('Origin is not allowed.',403);}
header("Content-Security-Policy: default-src 'none'; frame-ancestors 'none'; base-uri 'none'");header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');header('Cross-Origin-Resource-Policy: same-site');header('Cache-Control: no-store');
if(($_SERVER['REQUEST_METHOD']??'GET')==='OPTIONS'){header('Access-Control-Allow-Methods: GET, POST, PATCH, DELETE, OPTIONS');header('Access-Control-Allow-Headers: Content-Type, X-CSRF-Token, Idempotency-Key');http_response_code(204);exit;}
$secure=Env::get('APP_ENV','development')==='production';session_name(Env::get('APP_SESSION_NAME','adam_money_session'));session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>$secure,'httponly'=>true,'samesite'=>'Strict']);session_start();
$window=(int)Env::get('RATE_LIMIT_WINDOW_SECONDS','60');$limit=(int)Env::get('RATE_LIMIT_REQUESTS','120');$bucket=$_SESSION['rate']??['start'=>time(),'count'=>0];if(time()-$bucket['start']>=$window)$bucket=['start'=>time(),'count'=>0];if(++$bucket['count']>$limit){header('Retry-After: '.max(1,$window-(time()-$bucket['start'])));JsonResponse::error('Too many requests. Please wait and try again.',429);}$_SESSION['rate']=$bucket;
$timezone=new DateTimeZone(Env::get('APP_TIMEZONE','Europe/Amsterdam'));$manualDates=array_values(array_filter(array_map('trim',explode(',',Env::get('MANUAL_EDITABLE_DATES','')))));$service=new MoneyService(new MoneyRepository(Connection::create()),new DatePolicy($timezone,null,$manualDates),(int)Env::get('SINGLE_USER_ID','1'));$method=$_SERVER['REQUEST_METHOD']??'GET';$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);$path=preg_replace('#^/api#','',$path)?:'/';
try{
 if($method==='GET'&&$path==='/bootstrap')JsonResponse::success(['csrfToken'=>Csrf::token(),'timezone'=>$timezone->getName()]);
 if($method==='GET'&&preg_match('#^/months/(\d{4}-\d{2})$#',$path,$m))JsonResponse::success($service->month($m[1]));
 if($method==='GET'&&preg_match('#^/days/(\d{4}-\d{2}-\d{2})$#',$path,$m))JsonResponse::success($service->day($m[1]));
 if(!in_array($method,['GET','HEAD','OPTIONS'],true))Csrf::verify();
 if($method==='POST'&&preg_match('#^/days/(\d{4}-\d{2}-\d{2})/expenses$#',$path,$m)){[$valid,$errors]=ExpenseValidator::validate(Request::json());if($errors)JsonResponse::error('Please correct the highlighted fields.',422,$errors);$key=$_SERVER['HTTP_IDEMPOTENCY_KEY']??bin2hex(random_bytes(16));if(!preg_match('/^[A-Za-z0-9_-]{16,80}$/',$key))JsonResponse::error('Invalid idempotency key.',400);JsonResponse::success($service->add($m[1],$valid,$key),201);}
 if($method==='PATCH'&&preg_match('#^/expenses/(\d+)$#',$path,$m)){[$valid,$errors]=ExpenseValidator::validate(Request::json());if($errors)JsonResponse::error('Please correct the highlighted fields.',422,$errors);$service->update((int)$m[1],$valid);JsonResponse::success(['updated'=>true]);}
 if($method==='DELETE'&&preg_match('#^/expenses/(\d+)$#',$path,$m)){$service->delete((int)$m[1]);JsonResponse::success(['deleted'=>true]);}
 JsonResponse::error('Endpoint not found.',404);
}catch(PDOException $e){error_log($e->__toString());if($e->getCode()==='23000')JsonResponse::error('This request has already been processed.',409);JsonResponse::error('The service is temporarily unavailable.',500);}catch(InvalidArgumentException $e){JsonResponse::error($e->getMessage(),400);}catch(DomainException $e){JsonResponse::error($e->getMessage(),403);}catch(Throwable $e){error_log($e->__toString());JsonResponse::error(Env::get('APP_DEBUG','false')==='true'?$e->getMessage():'An unexpected error occurred.',500);}
