import { Copy, Link, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../services/api';

export function AdminPanel({ onClose, notify }) {
 const [data,setData]=useState(null),[form,setForm]=useState({name:'',email:''}),[errors,setErrors]=useState({}),[link,setLink]=useState('');
 const load=()=>api.admin().then(setData).catch(e=>setErrors({form:e.message}));useEffect(load,[]);
 const invite=async e=>{e.preventDefault();setErrors({});try{const result=await api.invite(form);setLink(result.inviteUrl);setForm({name:'',email:''});await load();}catch(err){setErrors(err.fields||{form:err.message});}};
 const copy=async()=>{await navigator.clipboard.writeText(link);notify('Invitation link copied.');};
 const removeUser=async user=>{if(!window.confirm(`Delete ${user.name}'s account and all of its data?`))return;try{await api.deleteUser(user.id);await load();notify('User deleted.');}catch(err){setErrors({form:err.message});}};
 const removeInvite=async inv=>{if(!window.confirm(`Delete the invitation for ${inv.email}?`))return;try{await api.deleteInvitation(inv.id);await load();notify('Invitation deleted.');}catch(err){setErrors({form:err.message});}};
 return <div className="modal-layer"><button className="scrim" aria-label="Close" onClick={onClose}/><section className="settings-modal admin-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Administrator</span><h2>People & invites</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header>{data&&<p>{data.used} of {data.limit} account places used.</p>}<form className="invite-form" onSubmit={invite}><input aria-label="Name" placeholder="Name" maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input aria-label="Email" type="email" placeholder="Email" maxLength="254" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary-btn"><Link size={16}/>Create invite</button></form>{Object.values(errors).map(e=><span className="field-error" key={e}>{e}</span>)}{link&&<div className="invite-link"><code>{link}</code><button className="icon-btn" onClick={copy}><Copy size={16}/></button></div>}<div className="admin-list">{data?.users.map(user=><article key={user.id}><div><strong>{user.name}</strong><small>{user.email} · {user.role}</small></div>{user.id!==data.currentUserId&&<button className="icon-btn danger" onClick={()=>removeUser(user)} aria-label={`Delete ${user.name}`}><Trash2 size={16}/></button>}</article>)}</div><h3>Pending invitations</h3><div className="admin-list">{data?.invitations.map(inv=><article key={inv.id}><div><strong>{inv.name}</strong><small>{inv.email} · Pending</small></div><button className="icon-btn danger" onClick={()=>removeInvite(inv)} aria-label={`Delete invitation for ${inv.email}`}><Trash2 size={16}/></button></article>)}</div></section></div>;
}
