import { Copy, Link, UserCheck, UserX, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../services/api';

export function AdminPanel({ onClose, notify }) {
 const [data,setData]=useState(null),[form,setForm]=useState({name:'',email:''}),[errors,setErrors]=useState({}),[link,setLink]=useState('');
 const load=()=>api.admin().then(setData).catch(e=>setErrors({form:e.message}));useEffect(load,[]);
 const invite=async e=>{e.preventDefault();setErrors({});try{const result=await api.invite(form);setLink(result.inviteUrl);setForm({name:'',email:''});await load();}catch(err){setErrors(err.fields||{form:err.message});}};
 const copy=async()=>{await navigator.clipboard.writeText(link);notify('Invitation link copied.');};
 return <div className="modal-layer"><button className="scrim" aria-label="Close" onClick={onClose}/><section className="settings-modal admin-modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Administrator</span><h2>People & invites</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header>{data&&<p>{data.used} of {data.limit} account places used.</p>}<form className="invite-form" onSubmit={invite}><input aria-label="Name" placeholder="Name" maxLength="80" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input aria-label="Email" type="email" placeholder="Email" maxLength="254" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><button className="primary-btn"><Link size={16}/>Create invite</button></form>{Object.values(errors).map(e=><span className="field-error" key={e}>{e}</span>)}{link&&<div className="invite-link"><code>{link}</code><button className="icon-btn" onClick={copy}><Copy size={16}/></button></div>}<div className="admin-list">{data?.users.map(user=><article key={user.id}><div><strong>{user.name}</strong><small>{user.email} · {user.role}</small></div><button className={`icon-btn ${user.is_active?'danger':''}`} onClick={async()=>{await api.setUserActive(user.id,!Boolean(user.is_active));await load();}} aria-label={user.is_active?'Disable user':'Enable user'}>{user.is_active?<UserX size={16}/>:<UserCheck size={16}/>}</button></article>)}</div><h3>Invitations</h3><div className="admin-list">{data?.invitations.map(inv=><article key={inv.id}><div><strong>{inv.name}</strong><small>{inv.email} · {inv.accepted_at?'Accepted':inv.revoked_at?'Revoked':'Pending'}</small></div>{!inv.accepted_at&&!inv.revoked_at&&<button className="icon-btn danger" onClick={async()=>{await api.revokeInvitation(inv.id);await load();}}><X size={16}/></button>}</article>)}</div></section></div>;
}
