import { Save, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../services/api';

export function BudgetEditor({ data, month, onClose, onSaved }) {
 const isFirstSetup=data.budget.firstSetup??data.budget.dailyBudgetCentimes==null;
 const isNewMonth=data.budget.needsMonthlyGoal&&!isFirstSetup;
 const effectiveFrom=data.budget.goalEffectiveFrom||`${month}-01`;
 const [form,setForm]=useState({dailyBudget:'',monthlyBudget:'',effectiveFrom}),[errors,setErrors]=useState({}),[busy,setBusy]=useState(false);
 useEffect(()=>setForm({dailyBudget:data.budget.dailyBudgetCentimes==null?'':(data.budget.dailyBudgetCentimes/100).toFixed(2),monthlyBudget:data.budget.monthlyBudgetCentimes==null?'':(data.budget.monthlyBudgetCentimes/100).toFixed(2),effectiveFrom}),[data,month,effectiveFrom]);
 useEffect(()=>{const closeOnEscape=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',closeOnEscape);return()=>document.removeEventListener('keydown',closeOnEscape);},[onClose]);
 const prorated=data.budget.proratedFirstMonth&&form.monthlyBudget!==''&&!Number.isNaN(Number(form.monthlyBudget))?(Number(form.monthlyBudget)*data.budget.remainingDays/data.budget.daysInMonth).toFixed(2):null;
 const submit=async e=>{e.preventDefault();setBusy(true);setErrors({});try{await api.updateBudget(form);await onSaved();onClose();}catch(err){setErrors(err.fields||{form:err.message});}finally{setBusy(false);}};
 const title=isFirstSetup?'Set your first goals':isNewMonth?'New month, new goals':'Edit your budget';
 const message=isFirstSetup?(data.budget.proratedFirstMonth?`Your account starts on ${effectiveFrom}. Enter a normal full-month goal and we will prorate it across the ${data.budget.remainingDays} remaining days.`:'Choose your daily and monthly targets to get started.'):isNewMonth?'A fresh month is here. Confirm or update your daily and monthly goals before you continue.':'Changes start on the effective date, so older budget history stays accurate.';
 return <div className="modal-layer"><button className="scrim" aria-label="Close" onClick={onClose}/><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="budget-title"><header><div><span className="eyebrow">{isNewMonth?'Monthly reset':'Personal targets'}</span><h2 id="budget-title">{title}</h2></div><button className="icon-btn" onClick={onClose}><X/></button></header><p>{message}</p><form className="auth-form" onSubmit={submit}><label>Daily target (DH)<input inputMode="decimal" value={form.dailyBudget} onChange={e=>setForm({...form,dailyBudget:e.target.value})}/></label>{errors.dailyBudget&&<span className="field-error">{errors.dailyBudget}</span>}<label>{data.budget.proratedFirstMonth?'Normal full-month goal (DH)':'Monthly goal (DH)'}<input inputMode="decimal" value={form.monthlyBudget} onChange={e=>setForm({...form,monthlyBudget:e.target.value})}/></label>{prorated&&<small className="proration-note">Your first target will be <strong>{prorated} DH</strong> for {data.budget.remainingDays} of {data.budget.daysInMonth} days.</small>}{errors.monthlyBudget&&<span className="field-error">{errors.monthlyBudget}</span>}<label>Effective from<input type="date" value={form.effectiveFrom} onChange={e=>setForm({...form,effectiveFrom:e.target.value})} readOnly={isFirstSetup||isNewMonth}/></label>{errors.effectiveFrom&&<span className="field-error">{errors.effectiveFrom}</span>}{errors.form&&<span className="field-error">{errors.form}</span>}<button className="primary-btn" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save monthly goals'}</button></form></section></div>;
}
